"""Alembic environment: the database URL and metadata come from the application itself."""

from logging.config import fileConfig
from typing import Any, Literal

from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy import CheckConstraint, create_engine, pool

from app.core.config import settings
from app.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def render_item(type_: str, obj: Any, _: AutogenContext) -> str | Literal[False] | None:
    """Skip CHECK constraints generated by `sa.Enum(create_constraint=True)`.

    The rendered `sa.Enum(...)` column already creates that constraint. Alembic's own
    detection relies on an attribute SQLAlchemy 2.1 no longer provides, so without this
    hook every enum column gets a duplicate CHECK constraint in autogenerated migrations.
    Returning None omits the item; False falls back to the default rendering.
    """
    if type_ == "check" and isinstance(obj, CheckConstraint) and obj._type_bound:
        return None
    return False


def run_migrations_offline() -> None:
    """Emit SQL to stdout (`alembic upgrade head --sql`) without connecting."""
    context.configure(
        url=settings.database_uri.render_as_string(hide_password=False),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_item=render_item,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(settings.database_uri, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_item=render_item,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
