"""Deterministic hourly electricity simulator for the demo data.

Every (meter, day) pair has its own random stream, so a day always produces the same readings
whether it is generated by a full seed or later by a top-up run.
"""

import math
import random
from collections.abc import Callable, Iterator
from dataclasses import dataclass
from datetime import date, datetime, time, timedelta
from decimal import Decimal
from typing import Any

from app.core.enums import MeterStatus
from app.core.timezone import APP_TIMEZONE
from app.services.electricity_usage_service import calculate_cost

HOURS_PER_DAY = 24
# Outdoor temperature drives air-conditioning: Hanoi peaks mid-July (day-of-year ~196).
_SEASON_PEAK_DAY_OF_YEAR = 196
_SEASON_AMPLITUDE = 0.4
_NIGHT_HOURS = frozenset((*range(0, 7), *range(19, 24)))


@dataclass(frozen=True)
class LoadProfile:
    """Share of a room's peak load per hour of a weekday, plus weekend/seasonal behaviour."""

    name: str
    hourly: tuple[float, ...]
    saturday: float
    sunday: float
    # Fraction of the load that follows outdoor temperature (air-conditioning).
    seasonal_sensitivity: float

    def __post_init__(self) -> None:
        if len(self.hourly) != HOURS_PER_DAY:
            raise ValueError(f"Profile {self.name} must have {HOURS_PER_DAY} hourly values")

    @property
    def weekday_peak_hours(self) -> float:
        """Energy of a normal weekday expressed in hours at peak load."""
        return sum(self.hourly)


def _hours(*segments: tuple[int, float]) -> tuple[float, ...]:
    """Build 24 hourly values from (number_of_hours, value) segments."""
    values = tuple(value for count, value in segments for _ in range(count))
    if len(values) != HOURS_PER_DAY:
        raise ValueError("Segments must cover exactly 24 hours")
    return values


# fmt: off
OFFICE = LoadProfile("office", (
    0.12, 0.12, 0.12, 0.12, 0.12, 0.15, 0.25, 0.45, 0.85, 1.00, 1.00, 0.95,
    0.65, 0.90, 1.05, 1.05, 0.95, 0.75, 0.45, 0.30, 0.25, 0.20, 0.15, 0.12,
), saturday=0.45, sunday=0.30, seasonal_sensitivity=0.35)
MEETING = LoadProfile("meeting", (
    0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.08, 0.20, 0.60, 0.90, 0.95, 0.80,
    0.30, 0.70, 0.95, 1.00, 0.85, 0.50, 0.20, 0.10, 0.08, 0.06, 0.05, 0.05,
), saturday=0.25, sunday=0.10, seasonal_sensitivity=0.35)
LOBBY = LoadProfile("lobby", (
    0.35, 0.35, 0.35, 0.35, 0.35, 0.35, 0.55, 0.80, 0.95, 1.00, 1.00, 1.00,
    1.00, 1.00, 1.00, 1.00, 1.00, 0.95, 0.85, 0.75, 0.65, 0.55, 0.45, 0.40,
), saturday=0.75, sunday=0.65, seasonal_sensitivity=0.25)
CANTEEN = LoadProfile("canteen", (
    0.20, 0.20, 0.20, 0.20, 0.20, 0.25, 0.45, 0.60, 0.45, 0.40, 0.70, 1.00,
    1.00, 0.65, 0.35, 0.30, 0.30, 0.45, 0.55, 0.35, 0.25, 0.20, 0.20, 0.20,
), saturday=0.35, sunday=0.25, seasonal_sensitivity=0.15)
PANTRY = LoadProfile("pantry", (
    0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.35, 0.60, 0.80, 0.70, 0.60, 0.75,
    0.90, 0.70, 0.55, 0.60, 0.55, 0.45, 0.35, 0.30, 0.28, 0.25, 0.25, 0.25,
), saturday=0.50, sunday=0.40, seasonal_sensitivity=0.10)
SERVER = LoadProfile("server", (
    0.92, 0.92, 0.92, 0.92, 0.92, 0.92, 0.94, 0.95, 0.97, 0.98, 1.00, 1.00,
    1.00, 1.00, 1.00, 1.00, 0.99, 0.98, 0.97, 0.96, 0.95, 0.94, 0.93, 0.92,
), saturday=0.97, sunday=0.95, seasonal_sensitivity=0.08)
HVAC = LoadProfile("hvac", (
    0.10, 0.10, 0.10, 0.10, 0.10, 0.20, 0.55, 0.80, 0.95, 1.00, 1.00, 1.00,
    0.95, 1.00, 1.00, 1.00, 0.95, 0.80, 0.45, 0.25, 0.15, 0.10, 0.10, 0.10,
), saturday=0.40, sunday=0.25, seasonal_sensitivity=0.60)
# fmt: on
SECURITY = LoadProfile(
    "security", _hours((6, 1.0), (12, 0.8), (6, 1.0)), 1.0, 1.0, seasonal_sensitivity=0.10
)
STORAGE = LoadProfile(
    "storage", _hours((8, 0.4), (10, 1.0), (6, 0.4)), 0.6, 0.5, seasonal_sensitivity=0.0
)


@dataclass(frozen=True)
class MeterLoad:
    """What the simulator needs to know about one meter."""

    meter_code: str
    floor_number: int
    profile: LoadProfile
    peak_kw: float
    three_phase: bool
    status: MeterStatus


@dataclass(frozen=True)
class HourlyReading:
    kwh: float
    voltage: float
    current: float
    power_factor: float


@dataclass(frozen=True)
class Anomaly:
    """`factor` multiplies the whole day; `night_load` raises night hours to that share of peak."""

    factor: float = 1.0
    night_load: float | None = None


@dataclass(frozen=True)
class DemoScenario:
    """Demo events anchored to `today` (local date of the most recent reading)."""

    today: date
    random_anomaly_probability: float = 0.03
    # (meter_code, days before today, anomaly): makes recent alerts predictable for the demo.
    forced_anomalies: tuple[tuple[str, int, Anomaly], ...] = (
        ("M003", 1, Anomaly(factor=2.3)),
        ("M017", 2, Anomaly(factor=1.6)),
        ("M029", 1, Anomaly(night_load=0.75)),
    )
    # Floor-wide increase during the last `floor_event_days` days.
    floor_event_number: int = 3
    # 1.32 rather than 1.25: the autumn seasonal decline eats ~5%, the dashboard should still
    # show roughly +25% week over week (above the 20% warning threshold).
    floor_event_factor: float = 1.32
    floor_event_days: int = 7
    inactive_since_days: int = 30
    maintenance_since_days: int = 2

    def has_data(self, meter: MeterLoad, day: date) -> bool:
        if meter.status is MeterStatus.INACTIVE:
            return day <= self.today - timedelta(days=self.inactive_since_days)
        if meter.status is MeterStatus.MAINTENANCE:
            return day <= self.today - timedelta(days=self.maintenance_since_days)
        return True

    def floor_factor(self, meter: MeterLoad, day: date) -> float:
        in_event = (self.today - day).days < self.floor_event_days
        if meter.floor_number == self.floor_event_number and in_event:
            return self.floor_event_factor
        return 1.0

    def forced_anomaly(self, meter: MeterLoad, day: date) -> Anomaly | None:
        days_ago = (self.today - day).days
        for meter_code, offset, anomaly in self.forced_anomalies:
            if meter_code == meter.meter_code and offset == days_ago:
                return anomaly
        return None


class UsageSimulator:
    def __init__(self, scenario: DemoScenario, random_seed: int) -> None:
        self.scenario = scenario
        self.random_seed = random_seed

    def day_readings(self, meter: MeterLoad, day: date) -> list[HourlyReading]:
        """24 hourly readings of `meter` on local `day` (deterministic)."""
        rng = random.Random(f"{self.random_seed}:{meter.meter_code}:{day.isoformat()}")
        profile = meter.profile
        day_factor = (
            _weekday_factor(profile, day)
            * _seasonal_factor(profile, day)
            * self.scenario.floor_factor(meter, day)
            * _clamp(rng.gauss(1.0, 0.05), 0.85, 1.15)
        )
        loads = [
            meter.peak_kw * share * day_factor * _clamp(rng.gauss(1.0, 0.06), 0.75, 1.25)
            for share in profile.hourly
        ]
        anomaly = self._anomaly(meter, day, rng)
        if anomaly is not None:
            loads = _apply_anomaly(loads, anomaly, meter.peak_kw, rng)
        return [self._electrical_values(load_kw, meter, rng) for load_kw in loads]

    def rows(
        self,
        meter_id: int,
        meter: MeterLoad,
        start: datetime,
        end: datetime,
        price_on: Callable[[date], Decimal],
    ) -> Iterator[dict[str, Any]]:
        """Insert-ready rows for hours in [start, end] (aware datetimes, local hour starts)."""
        day = start.astimezone(APP_TIMEZONE).date()
        last_day = end.astimezone(APP_TIMEZONE).date()
        while day <= last_day:
            if self.scenario.has_data(meter, day):
                price = price_on(day)
                for hour, reading in enumerate(self.day_readings(meter, day)):
                    recorded_at = datetime.combine(day, time(hour), tzinfo=APP_TIMEZONE)
                    if start <= recorded_at <= end:
                        kwh = Decimal(f"{reading.kwh:.3f}")
                        yield {
                            "meter_id": meter_id,
                            "recorded_at": recorded_at,
                            "kwh": kwh,
                            "voltage": Decimal(f"{reading.voltage:.2f}"),
                            "current": Decimal(f"{reading.current:.3f}"),
                            "power_factor": Decimal(f"{reading.power_factor:.3f}"),
                            "cost": calculate_cost(kwh, price),
                        }
            day += timedelta(days=1)

    def _anomaly(self, meter: MeterLoad, day: date, rng: random.Random) -> Anomaly | None:
        if meter.status is not MeterStatus.ACTIVE:
            return None
        forced = self.scenario.forced_anomaly(meter, day)
        if forced is not None:
            return forced
        if rng.random() >= self.scenario.random_anomaly_probability:
            return None
        if rng.random() < 0.5:
            return Anomaly(night_load=rng.uniform(0.6, 0.85))
        return Anomaly(factor=rng.uniform(1.3, 2.5))

    @staticmethod
    def _electrical_values(load_kw: float, meter: MeterLoad, rng: random.Random) -> HourlyReading:
        nominal_voltage = 380.0 if meter.three_phase else 220.0
        voltage = nominal_voltage + rng.gauss(0.0, nominal_voltage * 0.012)
        power_factor = rng.uniform(0.86, 0.97)
        phase_factor = math.sqrt(3) if meter.three_phase else 1.0
        current = load_kw * 1000 / (phase_factor * voltage * power_factor)
        return HourlyReading(
            kwh=max(load_kw, 0.0),  # average kW over one hour == kWh
            voltage=voltage,
            current=current,
            power_factor=power_factor,
        )


def _weekday_factor(profile: LoadProfile, day: date) -> float:
    weekday = day.weekday()
    if weekday == 5:
        return profile.saturday
    if weekday == 6:
        return profile.sunday
    return 1.0


def _seasonal_factor(profile: LoadProfile, day: date) -> float:
    angle = 2 * math.pi * (day.timetuple().tm_yday - _SEASON_PEAK_DAY_OF_YEAR) / 365.25
    return 1 + profile.seasonal_sensitivity * _SEASON_AMPLITUDE * math.cos(angle)


def _apply_anomaly(
    loads: list[float], anomaly: Anomaly, peak_kw: float, rng: random.Random
) -> list[float]:
    adjusted = [load * anomaly.factor for load in loads]
    if anomaly.night_load is not None:
        night_load = anomaly.night_load
        adjusted = [
            max(load, peak_kw * night_load * rng.uniform(0.9, 1.1))
            if hour in _NIGHT_HOURS
            else load
            for hour, load in enumerate(adjusted)
        ]
    return adjusted


def _clamp(value: float, low: float, high: float) -> float:
    return min(max(value, low), high)
